# Generated by Django 5.2.7 on 2025-11-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
